apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: hello
  annotations:
    description: 'Simple HTTP hello world server'
spec:
  components:
    - name: http-component
      type: component
      properties:
        image: file://./build/hello_s.wasm
      traits:
        - type: spreadscaler
          properties:
            instances: 1
    - name: httpserver
      type: capability
      properties:
        image: ghcr.io/wasmcloud/http-server:0.26.0
      traits:
        - type: link
          properties:
            target:
              name: http-component
            namespace: wasi
            package: http
            interfaces: [incoming-handler]
            source:
              config:
                - name: default-http
                  properties:
                    address: 0.0.0.0:8000
